import { expect, browser, $ } from '@wdio/globals'

describe('Lojinha híbrida', () => {
    it('Realizar login no app', async () => {
        const usuario = "marcos2025"
        const senha = "marcos2025"
        const txtUsuario = $('android=new UiSelector().resourceId("usuario")') 
        await txtUsuario.setValue(usuario)
        const txtSenha = $('android=new UiSelector().resourceId("senha")') 
        await txtSenha.setValue(senha)
        const btnEntrar = $('android=new UiSelector().resourceId("btn-entrar")') 
        await btnEntrar.click()
        const lblListaDeProduto = $('android=new UiSelector().packageName("com.example.lojinha").text("Lista de Produtos")')
        const listaDeProduto = await lblListaDeProduto.getText()
        expect(listaDeProduto).toEqual('Lista de Produtos')
        await driver.saveScreenshot('./LoginVálido.png')
    })
    it('Adicionar produto e componente', async () => {
        const btnAdicionarProduto = $('//android.view.View[@text="ADICIONAR PRODUTO"]')
        await btnAdicionarProduto.click()
        const txtNomeProduto = $('android=new UiSelector().resourceId("produtonome")')
        const txtValorProduto = $('android=new UiSelector().resourceId("produtovalor")')
        const txtCoresProduto = $('android=new UiSelector().resourceId("produtocores")')
        const btnSalvar = $('android=new UiSelector().resourceId("btn-salvar")')
        await txtNomeProduto.setValue("Produto de Teste5")
        await txtValorProduto.setValue("100.00")
        await txtCoresProduto.setValue("Azul, Vermelho")
        await btnSalvar.click()
        const btnAdicionarComponente = $('//android.view.View[@text="ADICIONAR COMPONENTE"]')
        await btnAdicionarComponente.click()
        const txtNomeComponente = $('android=new UiSelector().resourceId("componentenomeadicionar")')
        const txtQuantidadeComponente = $('android=new UiSelector().resourceId("componentequantidadeadicionar")')
        await txtNomeComponente.setValue("Componente de Teste")
        await txtQuantidadeComponente.setValue("10")
        const btnSalvarComponente = $('//android.view.View[@text="SALVAR COMPONENTE"]')
        await btnSalvarComponente.click()
        const btnListaDeProdutos = $('//android.view.View[@text="LISTA DE PRODUTOS"]')
        await expect(btnListaDeProdutos).toBeDisplayed()
        await btnListaDeProdutos.click()
        await driver.saveScreenshot('./TesteProduto.png')
    })
    it('Editar produto existente', async () => {
        const produtoExistente = $('//android.view.View[@text="Produto Editado"]')
        await produtoExistente.click()
        const txtNomeProduto = $('android=new UiSelector().resourceId("produtonome")')
        const txtValorProduto = $('android=new UiSelector().resourceId("produtovalor")')
        const txtCoresProduto = $('android=new UiSelector().resourceId("produtocores")')
        await txtNomeProduto.setValue("Produto Editado")
        await txtValorProduto.setValue("200.00")
        await txtCoresProduto.setValue("Verde, Amarelo")
        const btnSalvar = $('//android.widget.Button[@text="SALVAR"]')
        await btnSalvar.waitForDisplayed({ timeout: 10000 })
        await expect(btnSalvar).toBeDisplayed()
        await btnSalvar.click()
        const btnListaDeProdutos = $('//android.view.View[@text="LISTA DE PRODUTOS"]')
        await btnListaDeProdutos.click()
    })
    it('Remover produto', async () => {
        const btnDelete = $('(//android.view.View[@text="delete"])[5]')
        await btnDelete.waitForDisplayed({ timeout: 10000 })
        await expect(btnDelete).toBeDisplayed()
        await btnDelete.click()
    })
    it('Remover componente', async () => {
        const btnDelete = $('(//android.view.View[@text="delete"])[2]')
        await btnDelete.waitForDisplayed({ timeout: 10000 })
        await expect(btnDelete).toBeDisplayed()
        await btnDelete.click()
        const btnListaDeProdutos = $('//android.view.View[@text="LISTA DE PRODUTOS"]')
        await expect(btnListaDeProdutos).toBeDisplayed()
        await btnListaDeProdutos.click()
    })
})

